### ISSUE TITLE
Outgoing/ingoing links are counted wrong

### ISSUE THREAD

**Issue by MonoTovarisj** [jonatkins/ingress-intel-total-conversion#1009]
Seems like panning around will get you different ingoing and outgoing links count. Maybe the intel update screwed this up too, I get different counts just by clicking back and forth on the portals. Even get more outgoing links than should be possible, when no ultra link amp is present.

Screens below are taking mere seconds from each other, but with the difference that I selected a few other portals and zoomed/panned a bit around in between.
![outgoinglinks](https://cloud.githubusercontent.com/assets/3660683/8453271/4fda7214-1ff3-11e5-9300-6aef89abb70b.png)

**Comment by jonatkins** [comment]
The Niantic servers are returning the same links more than once, but with different link IDs

Looks like these duplicate links are synthetic - generated from the field data - and have IDs ending with things like "...b_ac" and "...b_ab" (where there's a matching "...b" field ID)

Not really sure what Niantic were thinking with this. The real links seem to be in the data still, so why synthesise them? And if there is a need to fake it, why not just do it client-side and reduce the data sent??

I'll experiment with completely ignoring such links, but I'm guessing there's some cases they're needed otherwise why did they add them in the first place

**Comment by flamusdiu** [comment]
Niantic does a lot of things they problem shouldn't and we have no idea why they do it. P

**Comment by jonatkins** [comment]
Been doing some tests - and it seems fine for IITC to ignore these faked links

Yes, occasionally there will be a field with some edges short enough not to be seen, but in general it works far far better like this, and doesn't have all the miscount issues.

fixed in aca3799a6a2394db99e7734eaf31e2d2a8c222e1
