### ISSUE TITLE
Offline map data on IITC mobile?

### ISSUE THREAD

**Issue by ghost** [jonatkins/ingress-intel-total-conversion#225]
Hi,
I was just wondering if it is planned to use offline map data someday?
This would be very useful to quickly check out the region without starting Ingress.
Especially on limited bandwith, after playing Ingress a little bit to much.

Currently it is faster (for me) by just starting Ingress.

Greetings
Michael

PS: As you probably can see; english isn't my native language. :)

**Comment by ppumkin** [comment]
This can work if we can get something like gps coordinate files and import them to an app called ViewRanger. Its dedicated for people who do allot of walking where there is never any internet. It has several topogrophical maps, like dedicated for cycling, walking routes with various levels of detail. Also you can download maps from open maps, googles or bing. It was made to be able to make waypoints and things like that. I would just love to see where the portal is because some remote portals, well, navigate in Ingress wont work well when theres no internet and you cant see the thing. Atleast this way I can select the portal, I know what I want to do there because I make a plan at home on gigabit internet. I get on my motorbike.. limited GPRS.. not good. Its good enough to hack, attack and establish links, with some delay.. but its OK. So... is there a way to export just portal locations to a GPS data package thing? :) Sorry for long post.

**Comment by nexushoratio** [comment]
ppumkin:  bookmark it

**Comment by ppumkin** [comment]
I contacted ViewRanger and they said I can use a POI map editor. So that is what I did, I found Click2Map with a free account, then use total map conversion to show me the LAT/LAN. On one screen I find portals I am interested in visiting and on the Click2Map I add them easily with a name. I export to KML and convert to GPX and import to ViewRanger. Now I download the kind of map I like in those areas, go Offline and can go the approximate location with no Internet. I start up Ingress and have GPRS, it takes maybe a minute or two to get the map tiles local but the portals are there. I can hack and do what I need. Close Ingress and walk to the next remote place.
Obviosly I am happy with this because I just want to know how to get the portal withou relying on internet. I am not concerned what fields or links or to whom it belongs to, because I use the Intel map at home and make a plan and decide where to go more or less and if I need any team mates to help establist high level portals... where most people wouldnt even bother going. In my area there are massive gaps with no portals, 20km+ . ViewRanger also told me they doing an online POI editor soon, that can be shared, exported, imported, etc.

**Comment by fkloft** [comment]
If that app supports geo: intents, you can simply use the "share"
option in the details panel. If it doesn't, you might want to suggest
that to the developers.

**Comment by ppumkin** [comment]
I cant see share on on any details panel? I mean there is a share but it only shared a screen shot with the ingress intel map. I want to copy that lat/long from ingress intel to the viewranger app. I am using iOs but I will check on my tablet maybe its there.

**Comment by fkloft** [comment]
Ah, I thought you were talking about IITCm on Android. But that won't work
on iOS.
On Android, there is a share button below the resonator details, from which
you can open any installed app that supports geo: intents.
