### ISSUE TITLE
New plugin: Highlight Infected Portals (i.e. portals with impossible resonator configurations) 

### ISSUE THREAD

**Issue by tb527** [jonatkins/ingress-intel-total-conversion#381]
Wouldn't it be nice to have a filter that highlights portals that have impossible configurations of resonators? This would show every visible instance of one agent owning more than one L7 or L8, or more than two L5 or L6, or more than  four L2, L3 or L4 resonators, Portals with impossible configurations would be deemed "infected". 

A portal that only has had one agent deploying resonators before hit with one of the new weapons would not be highlighted on the map since its configuration is not impossible.

**Comment by Speeddymon** [comment]
I can see how this would be used for guardian hunting since people seem to think that scrapers can NOT detect portals that have been hit with Jarvis/Ada (not true by the way from what I understand of how captures and scrapers work)

I would say there is use for this but the risk of getting banned outweighs the benefits.

**Comment by fkloft** [comment]
Not possible any longer

**Comment by Speeddymon** [comment]
I didn't even think about it but you're right. The resonators no longer are published without clicking on each portal, only portal health is.
